resources:
  containers:
  - container: dotnet-geert
    image: 'microsoft/dotnet:2.1-sdk'

pool: 'Hosted Ubuntu 1604'
container: dotnet-geert

variables:
  buildConfiguration: 'Release'
  system.debug: true

steps:
- script: |
    cd ContainerizedBuildSample
    dotnet build --configuration $(buildConfiguration)
    dotnet test --configuration $(buildConfiguration) --logger trx --filter "category!=integration"
    dotnet publish --configuration $(buildConfiguration)
  displayName: 'Build & Test'